---
apiVersion: v1
kind: Service
metadata:
  name: kubprojdec-service
spec:
  selector:
    app: kubproj-app
  ports:
    - protocol: 'TCP'
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1

kind: Deployment

metadata:
  name: kubprojectdeclarative
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kubproj-app
  template:
    metadata:
      labels:
        app: kubproj-app
    spec:
      containers:
        - name: kubproj
          image: catalunha/kubprojeto:1.2